use doctrine_manifest::is_scratch_directory;
use doctrine_manifest::{
    AgentManifest, AgentPack, DoctrineManifest, RfcStatus, SourcePolicy, Verbosity,
    filter_by_verbosity, front_matter, states_obligations,
};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::env;
use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::process;

const GENERATED_BANNER: &str = "<!--\nGENERATED FILE. DO NOT EDIT DIRECTLY.\nCanonical sources \
live under /foundations, /doctrines, /patterns,\n /boundaries, /reviews, and /agents.\n-->\n";

const DOCTRINE_PACKAGE_FILES: &[&str] = &[
    "README.md",
    "doctrine.md",
    "rationale.md",
    "decision-framework.md",
    "review-standard.md",
    "anti-patterns.md",
    "glossary.md",
    "references.md",
];

const FOUNDATION_FILES: &[&str] = &[
    "foundations/README.md",
    "foundations/normative-language.md",
    "foundations/invariants.md",
    "foundations/evidence.md",
    "foundations/trust-boundaries.md",
    "foundations/guarantee-honesty.md",
    "foundations/complexity-budget.md",
];

const PATTERN_FILES: &[&str] = &[
    "patterns/README.md",
    "patterns/sum-types.md",
    "patterns/opaque-newtypes.md",
    "patterns/smart-constructors.md",
    "patterns/typestate.md",
    "patterns/capability-types.md",
    "patterns/consuming-transitions.md",
    "patterns/validated-collections.md",
    "patterns/hybrid-state-machines.md",
    "patterns/explicit-uncertainty.md",
    "patterns/successor-capabilities.md",
    "patterns/executable-narrative.md",
];

const BOUNDARY_FILES: &[&str] = &[
    "boundaries/README.md",
    "boundaries/serde.md",
    "boundaries/database-decoding.md",
    "boundaries/http-and-rpc.md",
    "boundaries/messaging.md",
    "boundaries/configuration.md",
    "boundaries/filesystem.md",
    "boundaries/ffi.md",
];

const REVIEW_FILES: &[&str] = &[
    "reviews/README.md",
    "reviews/pre-implementation.md",
    "reviews/domain-model-review.md",
    "reviews/boundary-review.md",
    "reviews/typestate-review.md",
    "reviews/distributed-effects-review.md",
    "reviews/executable-narrative-review.md",
    "reviews/final-correctness-audit.md",
];

const DIST_README: &str = "dist/README.md";
const DIST_FULL: &str = "dist/full-doctrine.md";
const DIST_COMPACT: &str = "dist/compact-doctrine.md";

const RFC_ACCEPTED_DIRECTORY: &str = "rfcs/accepted";
const RFC_ACCEPTED_OVERVIEW: &str = "rfcs/accepted/overview.md";
const RFC_ACCEPTED_INDEX: &str = "rfcs/accepted/README.md";

/// The accepted-RFC index declares its own source, because it does not live under
/// `dist/` and a reader arriving at it directly has no other signal.
const RFC_INDEX_BANNER: &str = "<!--\nGENERATED FILE. DO NOT EDIT DIRECTLY.\nGenerated by \
bundle-agent-context from rfcs/accepted/overview.md and the\n front matter of each \
rfcs/accepted/RFC-*.md.\n-->\n";

const DOCTRINE_MAP_OVERVIEW: &str = "doctrines/map-overview.md";
const DOCTRINE_MAP: &str = "doctrines/map.md";

/// The coverage map names its own sources for the same reason the RFC index does: it sits
/// beside hand-maintained documents, where a reader has no directory to warn them.
const DOCTRINE_MAP_BANNER: &str = "<!--\nGENERATED FILE. DO NOT EDIT DIRECTLY.\nGenerated by \
bundle-agent-context from doctrines/map-overview.md,\n manifest/doctrines.yaml, and \
manifest/agents.yaml.\n-->\n";

#[derive(Debug, Deserialize)]
struct RfcMetadata {
    id: String,
    title: String,
    status: RfcStatus,
}

#[derive(Debug, Eq, PartialEq)]
struct GeneratedFile {
    path: PathBuf,
    content: String,
}

/// Everything one generated output needs in order to project a canonical source into
/// itself, plus the record of what that projection withheld.
///
/// The policy is chosen per source by manifest membership rather than by list position, so
/// a `canonical_sources` entry that happens to name a normative file is still projected
/// whole.
struct Projection<'a> {
    root: &'a Path,
    output_path: &'a Path,
    ceiling: Verbosity,
    doctrines: &'a DoctrineManifest,
    agents: &'a AgentManifest,
    withheld_sections: usize,
    withheld_sources: usize,
}

impl<'a> Projection<'a> {
    const fn new(
        root: &'a Path,
        output_path: &'a Path,
        ceiling: Verbosity,
        doctrines: &'a DoctrineManifest,
        agents: &'a AgentManifest,
    ) -> Self {
        Self {
            root,
            output_path,
            ceiling,
            doctrines,
            agents,
            withheld_sections: 0,
            withheld_sources: 0,
        }
    }

    fn policy(&self, relative: &str) -> SourcePolicy {
        if states_obligations(relative, self.doctrines, self.agents) {
            SourcePolicy::Normative
        } else {
            SourcePolicy::Tiered(self.ceiling)
        }
    }
}

/// The strongest verbosity the schema declares. An output at this ceiling withholds
/// nothing, which is what makes `dist/full-doctrine.md` the complete corpus projection.
const fn widest_ceiling() -> Verbosity {
    *Verbosity::ALL
        .last()
        .expect("the schema declares at least one verbosity")
}

/// The weakest verbosity the schema declares.
const fn narrowest_ceiling() -> Verbosity {
    *Verbosity::ALL
        .first()
        .expect("the schema declares at least one verbosity")
}

/// The note every filtered output carries, naming the ceiling it applied and what that
/// ceiling withheld.
///
/// Emitted even when nothing was withheld. Without it a reader cannot distinguish an
/// output that had nothing to withhold from one whose disclosure was forgotten, and a
/// reader who meets sections one through eight and then ten concludes that nine was never
/// written.
fn assembly_note(projection: &Projection, authority: &str) -> String {
    let withheld = match projection.withheld_sections {
        0 => "Nothing was withheld at this ceiling.".to_owned(),
        sections => format!(
            "Withheld: {sections} {} across {} {}, each marked in place.",
            plural(sections, "section", "sections"),
            projection.withheld_sources,
            plural(projection.withheld_sources, "source", "sources"),
        ),
    };
    format!(
        "\n## Assembly\n\nCeiling `{}`, {authority}. A section annotated above that ceiling is \
         withheld here. {withheld}\n\nObligations are never withheld. A doctrine's normative \
         file, every foundation, every agent overlay, and every review checklist carry no \
         annotation, and generation rejects one. Canonical sources carry every section, and \
         `dist/full-doctrine.md` carries the corpus with no ceiling applied.\n",
        projection.ceiling
    )
}

const fn plural(count: usize, singular: &'static str, plural: &'static str) -> &'static str {
    if count == 1 { singular } else { plural }
}

/// What this tool was asked to do.
///
/// Parsing the argument into this type is what lets the dispatch below be exhaustive.
/// Validating the raw string and then matching on it a second time left the invalid
/// cases representable at the point of use, so the dispatch needed an `unreachable!`
/// arm to restate a guarantee the earlier check had already established.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Command {
    Generate,
    Check,
}

impl Command {
    /// The command named by the argument list, or `None` when it names something else
    /// or carries trailing arguments.
    fn parse(arguments: &mut impl Iterator<Item = String>) -> Option<Self> {
        let command = match arguments.next()?.as_str() {
            "generate" => Self::Generate,
            "check" => Self::Check,
            _ => return None,
        };
        arguments.next().is_none().then_some(command)
    }
}

fn main() {
    let mut arguments = env::args().skip(1);
    let Some(command) = Command::parse(&mut arguments) else {
        eprintln!("usage: bundle-agent-context <generate|check>");
        process::exit(2);
    };

    let root = match env::current_dir() {
        Ok(path) => path,
        Err(error) => {
            eprintln!("bundle-agent-context: cannot read current directory: {error}");
            process::exit(2);
        }
    };
    let outputs = match build_outputs(&root) {
        Ok(outputs) => outputs,
        Err(error) => {
            eprintln!("bundle-agent-context: {error}");
            process::exit(1);
        }
    };

    let result = match command {
        Command::Generate => generate(&root, &outputs).map_err(CommandFailure::Incomplete),
        Command::Check => check(&root, &outputs),
    };
    if let Err(failure) = result {
        eprintln!("bundle-agent-context: {failure}");
        process::exit(failure.exit_code());
    }
}

fn build_outputs(root: &Path) -> Result<Vec<GeneratedFile>, String> {
    let doctrine_manifest: DoctrineManifest = read_yaml(root, "manifest/doctrines.yaml")?;
    let mut agent_manifest: AgentManifest = read_yaml(root, "manifest/agents.yaml")?;
    validate_manifest_paths(&doctrine_manifest, &agent_manifest)?;
    validate_curated_inventory(root)?;
    agent_manifest.packs.sort_by_key(|pack| pack.ordering);

    let mut outputs = vec![
        GeneratedFile {
            path: PathBuf::from(DIST_FULL),
            content: build_full(
                root,
                &doctrine_manifest,
                &agent_manifest,
                Path::new(DIST_FULL),
            )?,
        },
        GeneratedFile {
            path: PathBuf::from(DIST_COMPACT),
            content: build_compact(
                root,
                &doctrine_manifest,
                &agent_manifest,
                Path::new(DIST_COMPACT),
            )?,
        },
        GeneratedFile {
            path: PathBuf::from(RFC_ACCEPTED_INDEX),
            content: build_rfc_index(root)?,
        },
        GeneratedFile {
            path: PathBuf::from(DOCTRINE_MAP),
            content: build_doctrine_map(root, &doctrine_manifest, &agent_manifest)?,
        },
    ];

    let mut output_paths = BTreeSet::from([
        PathBuf::from(DIST_README),
        PathBuf::from(DIST_FULL),
        PathBuf::from(DIST_COMPACT),
    ]);
    for pack in &agent_manifest.packs {
        let output_path = PathBuf::from(&pack.output_path);
        if !output_paths.insert(output_path.clone()) {
            return Err(format!(
                "generated output path is duplicated: {}",
                output_path.display()
            ));
        }
        outputs.push(GeneratedFile {
            path: output_path.clone(),
            content: build_role_pack(
                root,
                pack,
                &doctrine_manifest,
                &agent_manifest,
                &output_path,
            )?,
        });
    }

    // The index of the distributions is built last, because it reports their sizes. It is
    // not itself a distribution, so it carries no assembly note, and it is projected at the
    // widest ceiling for the same reason `dist/full-doctrine.md` is: eliding from it would
    // hide the description of the elision. It excludes itself from the table it carries,
    // which is what keeps the table a fixed point rather than a value that changes every
    // time it is written.
    let mut distribution = generated_document("Generated doctrine distributions");
    let mut index_projection = Projection::new(
        root,
        Path::new(DIST_README),
        widest_ceiling(),
        &doctrine_manifest,
        &agent_manifest,
    );
    append_source(
        &mut index_projection,
        "agents/distribution.md",
        &mut distribution,
    )?;
    distribution.push_str(&size_table(&outputs));
    outputs.push(GeneratedFile {
        path: PathBuf::from(DIST_README),
        content: normalize_final_newline(distribution),
    });

    outputs.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(outputs)
}

/// A table of every generated distribution and its size.
///
/// A reader choosing a bundle needs to know what it costs, and a byte count written by
/// hand is a machine-derivable fact with nothing checking it. Deriving it from the bytes
/// just produced makes the table current because it was generated, not because someone
/// remembered. The token column is an estimate and says so: it divides by
/// [`BYTES_PER_TOKEN_ESTIMATE`], which is a rule of thumb for English prose, not a
/// tokenizer.
fn size_table(outputs: &[GeneratedFile]) -> String {
    let mut table = String::from(
        "\n---\n\n## Sizes\n\n| Distribution | Bytes | Approximate tokens |\n| --- | ---: | ---: |\n",
    );
    let mut rows: Vec<&GeneratedFile> = outputs
        .iter()
        .filter(|file| file.path.starts_with("dist"))
        .collect();
    rows.sort_by_key(|file| file.content.len());
    for file in rows {
        let bytes = file.content.len();
        let _ = writeln!(
            table,
            "| `{}` | {bytes} | {} |",
            file.path.display().to_string().replace('\\', "/"),
            bytes / BYTES_PER_TOKEN_ESTIMATE
        );
    }
    table.push_str(
        "\nThe token column divides bytes by a fixed estimate of four. It is a planning \
         figure for choosing a bundle against a context window, not a measurement: a real \
         count depends on the tokenizer.\n",
    );
    table
}

/// Bytes per token, as a planning estimate for English prose.
const BYTES_PER_TOKEN_ESTIMATE: usize = 4;

/// The complete corpus projection, at the widest ceiling the schema declares.
///
/// This is the artifact a reader consults to confirm that nothing was lost, so it applies
/// no ceiling and its note says so.
fn build_full(
    root: &Path,
    doctrines: &DoctrineManifest,
    agents: &AgentManifest,
    output_path: &Path,
) -> Result<String, String> {
    let mut projection = Projection::new(root, output_path, widest_ceiling(), doctrines, agents);
    let mut body = String::new();
    append_source(&mut projection, "README.md", &mut body)?;
    append_sources(&mut projection, FOUNDATION_FILES, &mut body)?;

    for doctrine in doctrines.active() {
        for file in DOCTRINE_PACKAGE_FILES {
            let path = format!("{}/{}", doctrine.package_path, file);
            append_source(&mut projection, &path, &mut body)?;
        }
    }

    append_sources(&mut projection, PATTERN_FILES, &mut body)?;
    append_sources(&mut projection, BOUNDARY_FILES, &mut body)?;
    append_sources(&mut projection, REVIEW_FILES, &mut body)?;
    append_source(&mut projection, "agents/shared.md", &mut body)?;

    let mut output = generated_document("Full Rust doctrine corpus");
    output.push_str(&assembly_note(
        &projection,
        "the widest the schema declares, applied by `bundle-agent-context`",
    ));
    output.push_str(&body);
    Ok(normalize_final_newline(output))
}

/// The hydration bundle, at the narrowest ceiling the schema declares.
///
/// Its name and its purpose are smallness, so it takes the tightest ceiling rather than a
/// value chosen separately from the vocabulary.
fn build_compact(
    root: &Path,
    doctrines: &DoctrineManifest,
    agents: &AgentManifest,
    output_path: &Path,
) -> Result<String, String> {
    let mut projection = Projection::new(root, output_path, narrowest_ceiling(), doctrines, agents);
    let mut body = String::new();
    append_source(&mut projection, "agents/compact-core.md", &mut body)?;
    append_source(&mut projection, "foundations/README.md", &mut body)?;
    append_source(
        &mut projection,
        "foundations/guarantee-honesty.md",
        &mut body,
    )?;
    append_source(
        &mut projection,
        "doctrines/0001-invalid-states/decision-framework.md",
        &mut body,
    )?;

    for doctrine in doctrines.active() {
        append_source(&mut projection, &doctrine.normative_path, &mut body)?;
    }

    append_source(&mut projection, "patterns/README.md", &mut body)?;
    append_source(
        &mut projection,
        "reviews/final-correctness-audit.md",
        &mut body,
    )?;
    append_source(&mut projection, "agents/shared.md", &mut body)?;

    let mut output = generated_document("Compact Rust doctrine hydration");
    output.push_str(&assembly_note(
        &projection,
        "the narrowest the schema declares, applied by `bundle-agent-context`",
    ));
    output.push_str(&body);
    Ok(normalize_final_newline(output))
}

/// Builds the accepted-RFC index from the directory and each RFC's front matter.
///
/// The inputs are the file set and metadata the RFCs already carry, so this view has
/// no hand-maintained source of its own to drift from.
fn build_rfc_index(root: &Path) -> Result<String, String> {
    let output_path = Path::new(RFC_ACCEPTED_INDEX);
    let overview_relative = Path::new(RFC_ACCEPTED_OVERVIEW);
    let overview = fs::read_to_string(root.join(overview_relative))
        .map_err(|error| format!("cannot read {RFC_ACCEPTED_OVERVIEW}: {error}"))?;
    let overview = rewrite_relative_links(root, overview_relative, output_path, &overview)?;

    // This index does not pass through `append_source`, so it needs its own call. Without
    // one, an annotation in the overview would be published verbatim into a generated file
    // that lives outside `dist/`. The overview is never a normative path, a foundation, or
    // a review checklist, so the widest ceiling applies without consulting a manifest.
    let overview = filter_by_verbosity(
        &overview,
        SourcePolicy::Tiered(widest_ceiling()),
        RFC_ACCEPTED_OVERVIEW,
    )
    .map_err(|error| format!("{RFC_ACCEPTED_OVERVIEW}: {error}"))?
    .text;

    let mut entries = Vec::new();
    for path in all_files(&root.join(RFC_ACCEPTED_DIRECTORY))? {
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| format!("unreadable file name under {RFC_ACCEPTED_DIRECTORY}"))?;
        let is_markdown = path.extension().and_then(|extension| extension.to_str()) == Some("md");
        if !name.starts_with("RFC-") || !is_markdown {
            continue;
        }
        let text = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        let metadata_text =
            front_matter(&text).map_err(|message| format!("{}: {message}", path.display()))?;
        let metadata: RfcMetadata = serde_yaml_ng::from_str(metadata_text)
            .map_err(|error| format!("cannot parse {} front matter: {error}", path.display()))?;
        entries.push((metadata, name.to_owned()));
    }
    entries.sort_by(|left, right| left.0.id.cmp(&right.0.id));

    let mut output = String::from(RFC_INDEX_BANNER);
    output.push('\n');
    output.push_str(overview.trim_end());
    output.push_str("\n\n## Index\n\n");
    output.push_str("| RFC | Decision | Status |\n| --- | --- | --- |\n");
    for (metadata, name) in &entries {
        writeln!(
            output,
            "| [{}]({}) | {} | {} |",
            metadata.id, name, metadata.title, metadata.status
        )
        .map_err(|error| format!("cannot render the accepted-RFC index: {error}"))?;
    }
    if entries.is_empty() {
        output.push_str("| none | no accepted RFCs | n/a |\n");
    }
    Ok(normalize_final_newline(output))
}

/// Builds the doctrine coverage map: which pack hydrates which doctrine.
///
/// Both inputs are manifests, so this view has no hand-maintained source to drift from. It
/// is the transpose of six `doctrine_selections` lists, which is information the corpus
/// carries but no document presents: the lists answer what one pack receives, and only
/// their transpose answers which packs carry one doctrine.
fn build_doctrine_map(
    root: &Path,
    doctrines: &DoctrineManifest,
    agents: &AgentManifest,
) -> Result<String, String> {
    let output_path = Path::new(DOCTRINE_MAP);
    let overview_relative = Path::new(DOCTRINE_MAP_OVERVIEW);
    let overview = fs::read_to_string(root.join(overview_relative))
        .map_err(|error| format!("cannot read {DOCTRINE_MAP_OVERVIEW}: {error}"))?;
    let overview = rewrite_relative_links(root, overview_relative, output_path, &overview)?;
    let overview = filter_by_verbosity(
        &overview,
        SourcePolicy::Tiered(widest_ceiling()),
        DOCTRINE_MAP_OVERVIEW,
    )
    .map_err(|error| format!("{DOCTRINE_MAP_OVERVIEW}: {error}"))?
    .text;

    let mut output = String::from(DOCTRINE_MAP_BANNER);
    output.push('\n');
    output.push_str(overview.trim_end());
    output.push_str("\n\n## Pack coverage\n\n| Doctrine | Status |");
    for pack in &agents.packs {
        // The header links to the pack it names, so a reader can move from a row straight
        // to the artifact the row describes.
        let output_path = pack
            .output_path
            .strip_prefix("doctrines/")
            .unwrap_or(&pack.output_path);
        write!(
            output,
            " [{}](../{}) |",
            title_case(pack.id.as_str()),
            output_path
        )
        .map_err(|error| format!("cannot render the coverage map: {error}"))?;
    }
    output.push_str("\n| --- | --- |");
    for _ in &agents.packs {
        output.push_str(" --- |");
    }
    output.push('\n');

    // Every doctrine that is active, plus any a pack selects regardless of status. A pack
    // may select a non-active doctrine and `build_role_pack` will hydrate it, so listing
    // only the active ones would let a row disappear from this view while the pack that
    // carries it is unchanged.
    for doctrine in doctrines.doctrines.iter().filter(|entry| {
        entry.status.is_active()
            || agents
                .packs
                .iter()
                .any(|pack| pack.doctrine_selections.contains(&entry.id))
    }) {
        write!(
            output,
            "| [{}]({}/README.md) | {} |",
            doctrine.id,
            relative_package(doctrine),
            doctrine.status
        )
        .map_err(|error| format!("cannot render the coverage map: {error}"))?;
        for pack in &agents.packs {
            // An excluded cell is rendered rather than left blank, so the row reads the
            // same in a screen reader as it does in a rendered table.
            let carried = pack.doctrine_selections.contains(&doctrine.id);
            output.push_str(if carried { " yes |" } else { " — |" });
        }
        output.push('\n');
    }
    Ok(normalize_final_newline(output))
}

/// A doctrine package path relative to the coverage map, which sits in the same directory
/// their package folders do.
fn relative_package(doctrine: &doctrine_manifest::DoctrineEntry) -> &str {
    doctrine
        .package_path
        .strip_prefix("doctrines/")
        .unwrap_or(&doctrine.package_path)
}

fn build_role_pack(
    root: &Path,
    pack: &AgentPack,
    doctrines: &DoctrineManifest,
    agents: &AgentManifest,
    output_path: &Path,
) -> Result<String, String> {
    let mut projection =
        Projection::new(root, output_path, pack.maximum_verbosity, doctrines, agents);
    let mut body = String::new();

    let mut included = BTreeSet::new();
    for path in &pack.canonical_sources {
        append_unique_source(&mut projection, path, &mut included, &mut body)?;
    }
    for doctrine_id in &pack.doctrine_selections {
        let doctrine = doctrines
            .doctrines
            .iter()
            .find(|entry| entry.id == *doctrine_id)
            .ok_or_else(|| format!("agent {} selects unknown doctrine {doctrine_id}", pack.id))?;
        append_unique_source(
            &mut projection,
            &doctrine.normative_path,
            &mut included,
            &mut body,
        )?;
    }
    for path in &pack.review_checklists {
        append_unique_source(&mut projection, path, &mut included, &mut body)?;
    }

    // The note is rendered from the ledger, so it is built after the sources and inserted
    // before them.
    let mut output = generated_document(&format!(
        "{} agent doctrine pack",
        title_case(pack.id.as_str())
    ));
    output.push('\n');
    output.push_str(&pack.purpose);
    output.push('\n');
    output.push_str(&assembly_note(
        &projection,
        &format!(
            "declared for the `{}` pack in `manifest/agents.yaml`",
            pack.id
        ),
    ));
    output.push_str(&body);
    Ok(normalize_final_newline(output))
}

fn append_sources(
    projection: &mut Projection,
    paths: &[&str],
    output: &mut String,
) -> Result<(), String> {
    for path in paths {
        append_source(projection, path, output)?;
    }
    Ok(())
}

/// Emit a source once per output.
///
/// The set is keyed on path alone, which is correct because one output applies one
/// ceiling, so a given file always projects identically within it. Any future cache that
/// spans outputs must key on the path and the policy together.
fn append_unique_source(
    projection: &mut Projection,
    path: &str,
    included: &mut BTreeSet<String>,
    output: &mut String,
) -> Result<(), String> {
    if included.insert(path.to_owned()) {
        append_source(projection, path, output)?;
    }
    Ok(())
}

fn append_source(
    projection: &mut Projection,
    relative: &str,
    output: &mut String,
) -> Result<(), String> {
    let relative_path = validate_relative_path(relative, "canonical source")?;
    let path = projection.root.join(&relative_path);
    let content =
        fs::read_to_string(&path).map_err(|error| format!("cannot read {relative}: {error}"))?;

    // Links are rewritten before anything is withheld, so every link in the file is
    // resolved and validated even when the section carrying it does not reach this output.
    // Reversed, a link in a file that appears only in a narrow pack would be checked by no
    // output at all.
    let content = rewrite_relative_links(
        projection.root,
        &relative_path,
        projection.output_path,
        &content,
    )?;
    let filtered = filter_by_verbosity(&content, projection.policy(relative), relative)
        .map_err(|error| format!("{relative}: {error}"))?;
    if !filtered.withheld.is_empty() {
        projection.withheld_sections += filtered.withheld.len();
        projection.withheld_sources += 1;
    }

    output.push_str("\n---\n\n## Source: `");
    output.push_str(relative);
    output.push_str("`\n\n");
    output.push_str(filtered.text.trim_end());
    output.push('\n');
    Ok(())
}

fn validate_manifest_paths(
    doctrines: &DoctrineManifest,
    agents: &AgentManifest,
) -> Result<(), String> {
    for doctrine in &doctrines.doctrines {
        validate_relative_path(&doctrine.package_path, "doctrine package_path")?;
        validate_relative_path(&doctrine.normative_path, "doctrine normative_path")?;
    }

    for pack in &agents.packs {
        for source in pack.canonical_sources.iter().chain(&pack.review_checklists) {
            validate_relative_path(source, "agent canonical source")?;
        }

        let output = validate_relative_path(&pack.output_path, "agent output_path")?;
        if !output.starts_with("dist/agents")
            || output.extension().and_then(|extension| extension.to_str()) != Some("md")
        {
            return Err(format!(
                "agent output_path must name a Markdown file under dist/agents: {}",
                pack.output_path
            ));
        }
    }
    Ok(())
}

fn validate_relative_path(value: &str, field: &str) -> Result<PathBuf, String> {
    if value.is_empty()
        || value.starts_with('/')
        || value.ends_with('/')
        || value.contains('\\')
        || value
            .split('/')
            .any(|component| component.is_empty() || matches!(component, "." | ".."))
        || !value.bytes().all(|byte| {
            byte.is_ascii_alphabetic()
                || byte.is_ascii_digit()
                || matches!(byte, b'.' | b'_' | b'-' | b'/')
        })
    {
        return Err(format!(
            "{field} is not a normalized repository-relative path: {value:?}"
        ));
    }

    let path = PathBuf::from(value);
    if path
        .components()
        .any(|component| !matches!(component, Component::Normal(_)))
    {
        return Err(format!(
            "{field} contains a non-normal path component: {value:?}"
        ));
    }
    Ok(path)
}

fn validate_curated_inventory(root: &Path) -> Result<(), String> {
    for (directory, expected) in [
        ("foundations", FOUNDATION_FILES),
        ("patterns", PATTERN_FILES),
        ("boundaries", BOUNDARY_FILES),
        ("reviews", REVIEW_FILES),
    ] {
        let expected: BTreeSet<PathBuf> = expected.iter().map(PathBuf::from).collect();
        let actual: BTreeSet<PathBuf> = all_files(&root.join(directory))?
            .into_iter()
            .filter(|path| path.extension().and_then(|extension| extension.to_str()) == Some("md"))
            .map(|path| {
                path.strip_prefix(root)
                    .map(Path::to_path_buf)
                    .map_err(|error| {
                        format!(
                            "cannot relativize inventory path {}: {error}",
                            path.display()
                        )
                    })
            })
            .collect::<Result<_, _>>()?;

        if actual != expected {
            let missing = expected
                .difference(&actual)
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>();
            let unbundled = actual
                .difference(&expected)
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>();
            return Err(format!(
                "{directory} bundle inventory differs from disk; missing [{}], unbundled [{}]",
                missing.join(", "),
                unbundled.join(", ")
            ));
        }
    }
    Ok(())
}

fn rewrite_relative_links(
    root: &Path,
    source_path: &Path,
    output_path: &Path,
    content: &str,
) -> Result<String, String> {
    let mut rewritten = String::with_capacity(content.len());
    let mut in_fence = false;

    for line in content.split_inclusive('\n') {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            in_fence = !in_fence;
            rewritten.push_str(line);
        } else if in_fence {
            rewritten.push_str(line);
        } else {
            rewritten.push_str(&rewrite_inline_links(root, source_path, output_path, line)?);
        }
    }

    Ok(rewritten)
}

fn rewrite_inline_links(
    root: &Path,
    source_path: &Path,
    output_path: &Path,
    line: &str,
) -> Result<String, String> {
    let mut rewritten = String::with_capacity(line.len());
    let mut cursor = 0;

    while let Some(offset) = line[cursor..].find("](") {
        let destination_start = cursor + offset + 2;
        rewritten.push_str(&line[cursor..destination_start]);
        let Some(close_offset) = line[destination_start..].find(')') else {
            rewritten.push_str(&line[destination_start..]);
            return Ok(rewritten);
        };
        let destination_end = destination_start + close_offset;
        let destination = &line[destination_start..destination_end];
        rewritten.push_str(&rewrite_destination(
            root,
            source_path,
            output_path,
            destination,
        )?);
        rewritten.push(')');
        cursor = destination_end + 1;
    }

    rewritten.push_str(&line[cursor..]);
    Ok(rewritten)
}

fn rewrite_destination(
    root: &Path,
    source_path: &Path,
    output_path: &Path,
    destination: &str,
) -> Result<String, String> {
    let leading = destination.len() - destination.trim_start().len();
    let trimmed = destination.trim_start();
    let (bracketed, target_start, target_end) = if let Some(rest) = trimmed.strip_prefix('<') {
        let Some(end) = rest.find('>') else {
            return Ok(destination.to_owned());
        };
        (true, 1, end + 1)
    } else {
        let end = trimmed.find(char::is_whitespace).unwrap_or(trimmed.len());
        (false, 0, end)
    };
    let target = &trimmed[target_start..target_end];

    if !is_relative_link(target) {
        return Ok(destination.to_owned());
    }

    let suffix_index = target.find(['#', '?']).unwrap_or(target.len());
    let path_part = &target[..suffix_index];
    let suffix = &target[suffix_index..];
    if path_part.is_empty() {
        return Ok(destination.to_owned());
    }

    let resolved = resolve_link_target(source_path, path_part)?;
    let absolute_target = root.join(&resolved);
    if !absolute_target.exists() {
        return Err(format!(
            "{} links to missing repository path {path_part:?}",
            source_path.display()
        ));
    }
    let output_parent = output_path
        .parent()
        .ok_or_else(|| format!("generated output {} has no parent", output_path.display()))?;
    let relative = relative_path(output_parent, &resolved);
    let mut replacement = relative.to_string_lossy().replace('\\', "/");
    if path_part.ends_with('/') {
        replacement.push('/');
    }
    replacement.push_str(suffix);

    let mut result = String::with_capacity(destination.len() + replacement.len());
    result.push_str(&destination[..leading]);
    if bracketed {
        result.push('<');
    }
    result.push_str(&replacement);
    if bracketed {
        result.push('>');
    }
    result.push_str(&trimmed[target_end + usize::from(bracketed)..]);
    Ok(result)
}

fn is_relative_link(target: &str) -> bool {
    if target.is_empty() || target.starts_with(['#', '/', '?']) || target.starts_with("//") {
        return false;
    }
    let path_end = target.find(['/', '#', '?']).unwrap_or(target.len());
    !target[..path_end].contains(':')
}

fn resolve_link_target(source_path: &Path, target: &str) -> Result<PathBuf, String> {
    let mut components: Vec<PathBuf> = source_path
        .parent()
        .into_iter()
        .flat_map(Path::components)
        .filter_map(|component| match component {
            Component::Normal(value) => Some(PathBuf::from(value)),
            _ => None,
        })
        .collect();

    for component in Path::new(target).components() {
        match component {
            Component::Normal(value) => components.push(PathBuf::from(value)),
            Component::CurDir => {}
            Component::ParentDir => {
                if components.pop().is_none() {
                    return Err(format!(
                        "{} link {target:?} escapes the repository",
                        source_path.display()
                    ));
                }
            }
            Component::RootDir | Component::Prefix(_) => {
                return Err(format!(
                    "{} link {target:?} is not repository-relative",
                    source_path.display()
                ));
            }
        }
    }

    Ok(components.into_iter().collect())
}

fn relative_path(from_directory: &Path, to: &Path) -> PathBuf {
    let from = from_directory.components().collect::<Vec<_>>();
    let to = to.components().collect::<Vec<_>>();
    let shared = from
        .iter()
        .zip(&to)
        .take_while(|(left, right)| left == right)
        .count();

    let mut relative = PathBuf::new();
    for _ in shared..from.len() {
        relative.push("..");
    }
    for component in &to[shared..] {
        relative.push(component.as_os_str());
    }
    relative
}

fn generated_document(title: &str) -> String {
    let mut output = String::from(GENERATED_BANNER);
    output.push('\n');
    output.push_str("# ");
    output.push_str(title);
    output.push('\n');
    output
}

fn normalize_final_newline(mut text: String) -> String {
    let length = text.trim_end().len();
    text.truncate(length);
    text.push('\n');
    text
}

fn read_yaml<T: for<'de> Deserialize<'de>>(root: &Path, relative: &str) -> Result<T, String> {
    let text = fs::read_to_string(root.join(relative))
        .map_err(|error| format!("cannot read {relative}: {error}"))?;
    serde_yaml_ng::from_str(&text).map_err(|error| format!("cannot parse {relative}: {error}"))
}

fn title_case(value: &str) -> String {
    let mut characters = value.chars();
    let Some(first) = characters.next() else {
        return String::new();
    };
    first.to_uppercase().chain(characters).collect()
}

fn generate(root: &Path, outputs: &[GeneratedFile]) -> Result<(), String> {
    let mut updated = 0;
    for output in outputs {
        let path = root.join(&output.path);
        let parent = path
            .parent()
            .ok_or_else(|| format!("output {} has no parent", output.path.display()))?;
        fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
        let current = fs::read_to_string(&path).ok();
        if current.as_deref() != Some(output.content.as_str()) {
            fs::write(&path, &output.content)
                .map_err(|error| format!("cannot write {}: {error}", output.path.display()))?;
            updated += 1;
        }
    }
    println!(
        "bundle-agent-context: updated {updated} of {} generated file(s)",
        outputs.len()
    );
    Ok(())
}

/// Why a command failed, when the answer changes what the caller should do next.
///
/// The caller here is CI. Stale bundles are an ordinary finding it can act on by
/// running `generate`; a tree it cannot read is a broken run that shows neither drift
/// nor its absence. Collapsing both into one string and one exit code erased that
/// distinction, which is what `RUST-DOC-0002-R003` exists to prevent.
enum CommandFailure {
    /// The committed bundles differ from what the canonical sources generate.
    Drift(Vec<String>),
    /// The command could not complete, so nothing is established either way.
    Incomplete(String),
}

impl CommandFailure {
    /// Distinct codes, so a caller need not parse the message to tell them apart.
    const fn exit_code(&self) -> i32 {
        match self {
            Self::Incomplete(_) => 1,
            Self::Drift(_) => 3,
        }
    }
}

impl fmt::Display for CommandFailure {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Drift(entries) => {
                write!(
                    formatter,
                    "generated drift detected:\n{}",
                    entries.join("\n")
                )
            }
            Self::Incomplete(reason) => write!(formatter, "{reason}"),
        }
    }
}

fn check(root: &Path, outputs: &[GeneratedFile]) -> Result<(), CommandFailure> {
    let mut drift = Vec::new();
    let expected: BTreeSet<PathBuf> = outputs.iter().map(|output| output.path.clone()).collect();

    for output in outputs {
        let path = root.join(&output.path);
        match fs::read_to_string(&path) {
            Ok(current) if current == output.content => {}
            Ok(_) => drift.push(format!("changed: {}", output.path.display())),
            Err(error) => drift.push(format!("missing: {} ({error})", output.path.display())),
        }
    }

    for path in all_files(&root.join("dist")).map_err(CommandFailure::Incomplete)? {
        let relative = path
            .strip_prefix(root)
            .map_err(|error| {
                CommandFailure::Incomplete(format!("cannot relativize {}: {error}", path.display()))
            })?
            .to_path_buf();
        if !expected.contains(&relative) {
            drift.push(format!("unexpected: {}", relative.display()));
        }
    }

    if drift.is_empty() {
        println!("bundle-agent-context: generated files are current");
        Ok(())
    } else {
        drift.sort();
        Err(CommandFailure::Drift(drift))
    }
}

/// Every file under `directory`, sorted.
///
/// Every directory this tool walks is one the repository requires, so any failure to
/// enumerate one aborts generation. Returning an empty list instead made a walk that
/// observed nothing indistinguishable from a directory that is genuinely empty: with
/// `rfcs/accepted` unlistable, generation rewrote the accepted-RFC index from its three
/// rows to "no accepted RFCs" and exited zero.
fn all_files(directory: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_files(directory, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_files(directory: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("cannot enumerate {}: {error}", directory.display()))?;
    // A per-entry failure is discarded by `filter_map(Result::ok)`, which drops a file
    // from the walk as quietly as an unreadable parent dropped all of them.
    for entry in entries {
        let entry = entry
            .map_err(|error| format!("cannot read an entry of {}: {error}", directory.display()))?;
        let path = entry.path();
        // The same sanctioned scratch space doctrine-lint skips. Without this, a
        // contributor's `foundations/wip/scratch.md` made `bundle-agent-context check`
        // fail and `generate` refuse, one command after doctrine-lint reported valid.
        if is_scratch_directory(&path) {
            continue;
        }
        // `Path::is_dir` and `Path::is_file` follow symbolic links and report `false`
        // for a metadata error, so a link is classified as whatever it points at and a
        // classification failure is indistinguishable from "neither". `file_type`
        // describes the entry itself and reports its own failure.
        let file_type = entry
            .file_type()
            .map_err(|error| format!("cannot classify {}: {error}", path.display()))?;
        if file_type.is_symlink() {
            return Err(format!(
                "{} is a symbolic link; generated output is built only from regular files \
                 inside the repository, because a link can name a target outside it",
                path.display()
            ));
        }
        if file_type.is_dir() {
            collect_files(&path, files)?;
        } else if file_type.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        AgentManifest, CommandFailure, DoctrineManifest, GENERATED_BANNER, GeneratedFile,
        Projection, Verbosity, all_files, append_source, check, generated_document,
        narrowest_ceiling, normalize_final_newline, rewrite_relative_links, title_case,
        validate_relative_path, widest_ceiling,
    };
    use std::fmt::Write as _;
    use std::fs;
    use std::path::{Path, PathBuf};

    /// Manifests carrying no entries, so a test can choose which paths state obligations
    /// rather than inheriting the repository's.
    fn manifests(normative: &[&str], checklists: &[&str]) -> (DoctrineManifest, AgentManifest) {
        let mut doctrines =
            String::from("schema_version: \"1.0\"\nrepository_version: \"0.0.0\"\ndoctrines:\n");
        if normative.is_empty() {
            doctrines = doctrines.replace("doctrines:\n", "doctrines: []\n");
        }
        for (index, path) in normative.iter().enumerate() {
            write!(
                doctrines,
                "  - id: RUST-DOC-{:04}\n    slug: s{index}\n    title: T\n    status: active\n    \
                 version: \"0.0.0\"\n    package_path: p{index}\n    normative_path: {path}\n    \
                 applies_to: []\n    risk_domains: []\n    foundation_dependencies: []\n    \
                 related_patterns: []\n    related_boundaries: []\n    related_case_studies: []\n    \
                 supersedes: []\n    superseded_by: null\n",
                index + 1
            )
            .expect("render a doctrine manifest fixture");
        }
        let mut agents = String::from("schema_version: \"1.0\"\npacks:\n");
        if checklists.is_empty() {
            agents = agents.replace("packs:\n", "packs: []\n");
        } else {
            agents.push_str(
                "  - id: shared\n    purpose: A purpose long enough to pass validation.\n    \
                 maximum_verbosity: focused\n    ordering: 10\n    canonical_sources: []\n    \
                 doctrine_selections: []\n    review_checklists:\n",
            );
            for path in checklists {
                writeln!(agents, "      - {path}").expect("render an agent manifest fixture");
            }
            agents.push_str("    output_path: dist/agents/shared.md\n");
        }
        (
            serde_yaml_ng::from_str(&doctrines).expect("doctrine manifest fixture"),
            serde_yaml_ng::from_str(&agents).expect("agent manifest fixture"),
        )
    }

    fn scratch(name: &str) -> PathBuf {
        let path = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-{name}-{}",
            std::process::id()
        ));
        fs::create_dir_all(&path).expect("create temporary test directory");
        path
    }

    #[test]
    fn generated_document_starts_with_required_banner() {
        let document = generated_document("Example");
        assert!(document.starts_with(GENERATED_BANNER));
        assert!(document.contains("# Example\n"));
    }

    #[test]
    fn source_append_has_provenance_and_normalized_tail() {
        let temporary = scratch("append");
        fs::write(temporary.join("source.md"), "# Source\n\nBody\n\n").expect("write test source");

        let (doctrines, agents) = manifests(&[], &[]);
        let output_path = PathBuf::from("dist/output.md");
        let mut projection = Projection::new(
            &temporary,
            &output_path,
            widest_ceiling(),
            &doctrines,
            &agents,
        );
        let mut output = String::new();
        append_source(&mut projection, "source.md", &mut output).expect("append source");
        let output = normalize_final_newline(output);

        assert!(output.contains("## Source: `source.md`"));
        assert!(output.ends_with("Body\n"));
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }

    /// Links are rewritten before anything is withheld. Reversed, a link inside a section
    /// that no narrow pack receives would be validated by no output at all, and a broken
    /// link in a file that appears only in such a pack would ship.
    #[test]
    fn link_targets_are_validated_before_content_is_withheld() {
        let temporary = scratch("ordering");
        fs::write(
            temporary.join("source.md"),
            "# Source\n\n## Detail\n\n<!-- verbosity: exhaustive -->\n\n\
             See [gone](missing-target.md).\n",
        )
        .expect("write test source");

        let (doctrines, agents) = manifests(&[], &[]);
        let output_path = PathBuf::from("dist/output.md");
        let mut projection = Projection::new(
            &temporary,
            &output_path,
            narrowest_ceiling(),
            &doctrines,
            &agents,
        );
        let mut output = String::new();
        let error = append_source(&mut projection, "source.md", &mut output)
            .expect_err("a missing link target must fail even inside a withheld section");
        assert!(
            error.contains("missing-target.md"),
            "unexpected error: {error}"
        );
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }

    /// A file that states obligations carries no annotation, and generation refuses one
    /// rather than treating it as a no-op. `RUST-DOC-0011-R018` is the reason.
    #[test]
    fn an_annotation_in_a_file_that_states_obligations_stops_generation() {
        let temporary = scratch("normative");
        fs::create_dir_all(temporary.join("foundations")).expect("create foundations");
        fs::create_dir_all(temporary.join("agents")).expect("create agents");
        let annotated = "# Rules\n\n## Detail\n\n<!-- verbosity: exhaustive -->\n\nProse.\n";
        fs::write(temporary.join("rules.md"), annotated).expect("write normative source");
        fs::write(temporary.join("foundations/x.md"), annotated).expect("write foundation");
        // An overlay is an obligation document: `agents/shared.md` is titled "Shared agent
        // obligations". Omitting this class let an annotation withhold those rules from
        // every role pack while both tools exited zero.
        fs::write(temporary.join("agents/shared.md"), annotated).expect("write overlay");
        fs::write(temporary.join("gate.md"), annotated).expect("write checklist");

        let (doctrines, agents) = manifests(&["rules.md"], &["gate.md"]);
        let output_path = PathBuf::from("dist/output.md");
        for relative in [
            "rules.md",
            "foundations/x.md",
            "agents/shared.md",
            "gate.md",
        ] {
            let mut projection = Projection::new(
                &temporary,
                &output_path,
                widest_ceiling(),
                &doctrines,
                &agents,
            );
            let mut output = String::new();
            let error = append_source(&mut projection, relative, &mut output)
                .expect_err("an annotation in a file that states obligations must be rejected");
            assert!(
                error.contains("states obligations"),
                "{relative} produced an unexpected error: {error}"
            );
        }
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }

    /// A source above the ceiling is withheld and the projection records it, so the
    /// assembly note can state a count rather than a claim.
    #[test]
    fn a_withheld_section_is_replaced_by_a_receipt_and_counted() {
        let temporary = scratch("withheld");
        fs::write(
            temporary.join("source.md"),
            "# Source\n\n## Kept\n\nKept prose.\n\n## Detail\n\n<!-- verbosity: exhaustive -->\n\n\
             Withheld prose.\n",
        )
        .expect("write test source");

        let (doctrines, agents) = manifests(&[], &[]);
        let output_path = PathBuf::from("dist/output.md");
        let mut projection = Projection::new(
            &temporary,
            &output_path,
            Verbosity::Detailed,
            &doctrines,
            &agents,
        );
        let mut output = String::new();
        append_source(&mut projection, "source.md", &mut output).expect("append source");

        assert!(output.contains("Kept prose."));
        assert!(!output.contains("Withheld prose."));
        assert!(output.contains("> [!NOTE]"));
        assert!(output.contains("Canonical text: `source.md`."));
        assert_eq!(projection.withheld_sections, 1);
        assert_eq!(projection.withheld_sources, 1);
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }

    #[test]
    fn role_title_is_stable() {
        assert_eq!(title_case("planner"), "Planner");
        assert_eq!(title_case(""), "");
    }

    #[test]
    fn relocated_sources_link_back_to_canonical_files() {
        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-links-{}",
            std::process::id()
        ));
        fs::create_dir_all(temporary.join("foundations")).expect("create foundation directory");
        fs::create_dir_all(temporary.join("agents")).expect("create agent directory");
        fs::write(
            temporary.join("foundations/invariants.md"),
            "# Invariants\n",
        )
        .expect("write target");
        let source = "Read [invariants](../foundations/invariants.md#inventory).\n";

        let rewritten = rewrite_relative_links(
            &temporary,
            Path::new("agents/shared.md"),
            Path::new("dist/agents/shared.md"),
            source,
        )
        .expect("rewrite relative link");

        assert_eq!(
            rewritten,
            "Read [invariants](../../foundations/invariants.md#inventory).\n"
        );
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }

    #[test]
    fn manifest_paths_cannot_escape_repository() {
        assert!(validate_relative_path("agents/shared.md", "test").is_ok());
        assert!(validate_relative_path("../outside.md", "test").is_err());
        assert!(validate_relative_path("agents/../outside.md", "test").is_err());
        assert!(validate_relative_path("/outside.md", "test").is_err());
    }

    /// A directory the bundler cannot enumerate must abort the walk. Returning an empty
    /// list made an unlistable `rfcs/accepted` indistinguishable from an empty one, so
    /// generation rewrote the accepted-RFC index to "no accepted RFCs" and exited zero.
    #[cfg(unix)]
    #[test]
    fn an_unlistable_directory_aborts_the_walk() {
        use std::os::unix::fs::PermissionsExt;

        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-unlistable-{}",
            std::process::id()
        ));
        let locked = temporary.join("locked");
        fs::create_dir_all(&locked).expect("create directory");
        fs::write(locked.join("entry.md"), "body\n").expect("write test entry");
        fs::set_permissions(&locked, fs::Permissions::from_mode(0o111))
            .expect("remove read permission");

        // A process that overrides permission bits cannot construct the condition.
        let enforced = fs::read_dir(&locked).is_err();
        let walked = all_files(&locked);

        fs::set_permissions(&locked, fs::Permissions::from_mode(0o755))
            .expect("restore directory permissions");
        fs::remove_dir_all(&temporary).expect("remove temporary test directory");

        if enforced {
            let error = walked.expect_err("an unlistable directory must abort the walk");
            assert!(error.contains("cannot enumerate"), "{error}");
        }
    }

    /// A symbolic link must abort the walk rather than be classified as its target.
    /// `Path::is_file` follows the link, so one placed in `rfcs/accepted` published a
    /// second index row for content the repository does not contain.
    #[cfg(unix)]
    #[test]
    fn a_symbolic_link_aborts_the_walk() {
        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-symlink-{}",
            std::process::id()
        ));
        let directory = temporary.join("walk");
        fs::create_dir_all(&directory).expect("create directory");
        let outside = temporary.join("outside.md");
        fs::write(&outside, "outside the walk\n").expect("write link target");
        std::os::unix::fs::symlink(&outside, directory.join("linked.md"))
            .expect("create symbolic link");

        let walked = all_files(&directory);

        fs::remove_dir_all(&temporary).expect("remove temporary test directory");
        let error = walked.expect_err("a symbolic link must abort the walk");
        assert!(error.contains("is a symbolic link"), "{error}");
    }

    #[test]
    fn check_rejects_non_markdown_orphans_in_dist() {
        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-orphans-{}",
            std::process::id()
        ));
        fs::create_dir_all(temporary.join("dist")).expect("create dist directory");
        fs::write(temporary.join("dist/expected.md"), "expected\n").expect("write expected file");
        fs::write(temporary.join("dist/orphan.bin"), [0_u8, 1, 2]).expect("write orphan file");
        let outputs = [GeneratedFile {
            path: Path::new("dist/expected.md").to_path_buf(),
            content: "expected\n".to_owned(),
        }];

        let failure = check(&temporary, &outputs).expect_err("orphan must fail check mode");
        fs::remove_dir_all(temporary).expect("remove temporary test directory");

        // Match the variant, not the wording: an orphan is drift a caller can fix by
        // regenerating, and it must not be reported as a run that could not complete.
        let CommandFailure::Drift(entries) = &failure else {
            panic!("an orphan is drift, not an incomplete run; got {failure}");
        };
        assert!(
            entries
                .iter()
                .any(|entry| entry == "unexpected: dist/orphan.bin"),
            "{entries:?}"
        );
        assert_eq!(
            failure.exit_code(),
            3,
            "drift must be separable by exit code"
        );
    }
}
