use doctrine_manifest::{AgentManifest, AgentPack, DoctrineManifest, front_matter};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::process;

const GENERATED_BANNER: &str = "<!--\nGENERATED FILE. DO NOT EDIT DIRECTLY.\nCanonical sources \
live under /foundations, /doctrines, /patterns,\n /boundaries, /reviews, and /agents.\n-->\n";

const DOCTRINE_PACKAGE_FILES: &[&str] = &[
    "README.md",
    "doctrine.md",
    "rationale.md",
    "decision-framework.md",
    "review-standard.md",
    "anti-patterns.md",
    "glossary.md",
    "references.md",
];

const FOUNDATION_FILES: &[&str] = &[
    "foundations/README.md",
    "foundations/normative-language.md",
    "foundations/invariants.md",
    "foundations/evidence.md",
    "foundations/trust-boundaries.md",
    "foundations/guarantee-honesty.md",
    "foundations/complexity-budget.md",
];

const PATTERN_FILES: &[&str] = &[
    "patterns/README.md",
    "patterns/sum-types.md",
    "patterns/opaque-newtypes.md",
    "patterns/smart-constructors.md",
    "patterns/typestate.md",
    "patterns/capability-types.md",
    "patterns/consuming-transitions.md",
    "patterns/validated-collections.md",
    "patterns/hybrid-state-machines.md",
    "patterns/explicit-uncertainty.md",
    "patterns/successor-capabilities.md",
    "patterns/executable-narrative.md",
];

const BOUNDARY_FILES: &[&str] = &[
    "boundaries/README.md",
    "boundaries/serde.md",
    "boundaries/database-decoding.md",
    "boundaries/http-and-rpc.md",
    "boundaries/messaging.md",
    "boundaries/configuration.md",
    "boundaries/filesystem.md",
    "boundaries/ffi.md",
];

const REVIEW_FILES: &[&str] = &[
    "reviews/README.md",
    "reviews/pre-implementation.md",
    "reviews/domain-model-review.md",
    "reviews/boundary-review.md",
    "reviews/typestate-review.md",
    "reviews/distributed-effects-review.md",
    "reviews/executable-narrative-review.md",
    "reviews/final-correctness-audit.md",
];

const DIST_README: &str = "dist/README.md";
const DIST_FULL: &str = "dist/full-doctrine.md";
const DIST_COMPACT: &str = "dist/compact-doctrine.md";

const RFC_ACCEPTED_DIRECTORY: &str = "rfcs/accepted";
const RFC_ACCEPTED_OVERVIEW: &str = "rfcs/accepted/overview.md";
const RFC_ACCEPTED_INDEX: &str = "rfcs/accepted/README.md";

/// The accepted-RFC index declares its own source, because it does not live under
/// `dist/` and a reader arriving at it directly has no other signal.
const RFC_INDEX_BANNER: &str = "<!--\nGENERATED FILE. DO NOT EDIT DIRECTLY.\nGenerated by \
bundle-agent-context from rfcs/accepted/overview.md and the\n front matter of each \
rfcs/accepted/RFC-*.md.\n-->\n";

#[derive(Debug, Deserialize)]
struct RfcMetadata {
    id: String,
    title: String,
    status: String,
}

#[derive(Debug, Eq, PartialEq)]
struct GeneratedFile {
    path: PathBuf,
    content: String,
}

/// What this tool was asked to do.
///
/// Parsing the argument into this type is what lets the dispatch below be exhaustive.
/// Validating the raw string and then matching on it a second time left the invalid
/// cases representable at the point of use, so the dispatch needed an `unreachable!`
/// arm to restate a guarantee the earlier check had already established.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Command {
    Generate,
    Check,
}

impl Command {
    /// The command named by the argument list, or `None` when it names something else
    /// or carries trailing arguments.
    fn parse(arguments: &mut impl Iterator<Item = String>) -> Option<Self> {
        let command = match arguments.next()?.as_str() {
            "generate" => Self::Generate,
            "check" => Self::Check,
            _ => return None,
        };
        arguments.next().is_none().then_some(command)
    }
}

fn main() {
    let mut arguments = env::args().skip(1);
    let Some(command) = Command::parse(&mut arguments) else {
        eprintln!("usage: bundle-agent-context <generate|check>");
        process::exit(2);
    };

    let root = match env::current_dir() {
        Ok(path) => path,
        Err(error) => {
            eprintln!("bundle-agent-context: cannot read current directory: {error}");
            process::exit(2);
        }
    };
    let outputs = match build_outputs(&root) {
        Ok(outputs) => outputs,
        Err(error) => {
            eprintln!("bundle-agent-context: {error}");
            process::exit(1);
        }
    };

    let result = match command {
        Command::Generate => generate(&root, &outputs),
        Command::Check => check(&root, &outputs),
    };
    if let Err(error) = result {
        eprintln!("bundle-agent-context: {error}");
        process::exit(1);
    }
}

fn build_outputs(root: &Path) -> Result<Vec<GeneratedFile>, String> {
    let doctrine_manifest: DoctrineManifest = read_yaml(root, "manifest/doctrines.yaml")?;
    let mut agent_manifest: AgentManifest = read_yaml(root, "manifest/agents.yaml")?;
    validate_manifest_paths(&doctrine_manifest, &agent_manifest)?;
    validate_curated_inventory(root)?;
    agent_manifest.packs.sort_by_key(|pack| pack.ordering);

    let mut outputs = Vec::new();

    let mut distribution = generated_document("Generated doctrine distributions");
    append_source(
        root,
        "agents/distribution.md",
        Path::new(DIST_README),
        &mut distribution,
    )?;
    outputs.push(GeneratedFile {
        path: PathBuf::from(DIST_README),
        content: distribution,
    });

    outputs.push(GeneratedFile {
        path: PathBuf::from(DIST_FULL),
        content: build_full(root, &doctrine_manifest, Path::new(DIST_FULL))?,
    });
    outputs.push(GeneratedFile {
        path: PathBuf::from(DIST_COMPACT),
        content: build_compact(root, &doctrine_manifest, Path::new(DIST_COMPACT))?,
    });
    outputs.push(GeneratedFile {
        path: PathBuf::from(RFC_ACCEPTED_INDEX),
        content: build_rfc_index(root)?,
    });

    let mut output_paths = BTreeSet::from([
        PathBuf::from(DIST_README),
        PathBuf::from(DIST_FULL),
        PathBuf::from(DIST_COMPACT),
    ]);
    for pack in &agent_manifest.packs {
        let output_path = PathBuf::from(&pack.output_path);
        if !output_paths.insert(output_path.clone()) {
            return Err(format!(
                "generated output path is duplicated: {}",
                output_path.display()
            ));
        }
        outputs.push(GeneratedFile {
            path: output_path.clone(),
            content: build_role_pack(root, pack, &doctrine_manifest, &output_path)?,
        });
    }

    outputs.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(outputs)
}

fn build_full(
    root: &Path,
    doctrines: &DoctrineManifest,
    output_path: &Path,
) -> Result<String, String> {
    let mut output = generated_document("Full Rust doctrine corpus");
    append_source(root, "README.md", output_path, &mut output)?;
    append_sources(root, FOUNDATION_FILES, output_path, &mut output)?;

    for doctrine in doctrines.active() {
        for file in DOCTRINE_PACKAGE_FILES {
            let path = format!("{}/{}", doctrine.package_path, file);
            append_source(root, &path, output_path, &mut output)?;
        }
    }

    append_sources(root, PATTERN_FILES, output_path, &mut output)?;
    append_sources(root, BOUNDARY_FILES, output_path, &mut output)?;
    append_sources(root, REVIEW_FILES, output_path, &mut output)?;
    append_source(root, "agents/shared.md", output_path, &mut output)?;
    Ok(normalize_final_newline(output))
}

fn build_compact(
    root: &Path,
    doctrines: &DoctrineManifest,
    output_path: &Path,
) -> Result<String, String> {
    let mut output = generated_document("Compact Rust doctrine hydration");
    append_source(root, "agents/compact-core.md", output_path, &mut output)?;
    append_source(root, "foundations/README.md", output_path, &mut output)?;
    append_source(
        root,
        "foundations/guarantee-honesty.md",
        output_path,
        &mut output,
    )?;
    append_source(
        root,
        "doctrines/0001-invalid-states/decision-framework.md",
        output_path,
        &mut output,
    )?;

    for doctrine in doctrines.active() {
        append_source(root, &doctrine.normative_path, output_path, &mut output)?;
    }

    append_source(root, "patterns/README.md", output_path, &mut output)?;
    append_source(
        root,
        "reviews/final-correctness-audit.md",
        output_path,
        &mut output,
    )?;
    append_source(root, "agents/shared.md", output_path, &mut output)?;
    Ok(normalize_final_newline(output))
}

/// Builds the accepted-RFC index from the directory and each RFC's front matter.
///
/// The inputs are the file set and metadata the RFCs already carry, so this view has
/// no hand-maintained source of its own to drift from.
fn build_rfc_index(root: &Path) -> Result<String, String> {
    let output_path = Path::new(RFC_ACCEPTED_INDEX);
    let overview_relative = Path::new(RFC_ACCEPTED_OVERVIEW);
    let overview = fs::read_to_string(root.join(overview_relative))
        .map_err(|error| format!("cannot read {RFC_ACCEPTED_OVERVIEW}: {error}"))?;
    let overview = rewrite_relative_links(root, overview_relative, output_path, &overview)?;

    let mut entries = Vec::new();
    for path in all_files(&root.join(RFC_ACCEPTED_DIRECTORY))? {
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| format!("unreadable file name under {RFC_ACCEPTED_DIRECTORY}"))?;
        let is_markdown = path.extension().and_then(|extension| extension.to_str()) == Some("md");
        if !name.starts_with("RFC-") || !is_markdown {
            continue;
        }
        let text = fs::read_to_string(&path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        let metadata_text =
            front_matter(&text).map_err(|message| format!("{}: {message}", path.display()))?;
        let metadata: RfcMetadata = serde_yaml_ng::from_str(metadata_text)
            .map_err(|error| format!("cannot parse {} front matter: {error}", path.display()))?;
        entries.push((metadata, name.to_owned()));
    }
    entries.sort_by(|left, right| left.0.id.cmp(&right.0.id));

    let mut output = String::from(RFC_INDEX_BANNER);
    output.push('\n');
    output.push_str(overview.trim_end());
    output.push_str("\n\n## Index\n\n");
    output.push_str("| RFC | Decision | Status |\n| --- | --- | --- |\n");
    for (metadata, name) in &entries {
        writeln!(
            output,
            "| [{}]({}) | {} | {} |",
            metadata.id, name, metadata.title, metadata.status
        )
        .map_err(|error| format!("cannot render the accepted-RFC index: {error}"))?;
    }
    if entries.is_empty() {
        output.push_str("| none | no accepted RFCs | n/a |\n");
    }
    Ok(normalize_final_newline(output))
}

fn build_role_pack(
    root: &Path,
    pack: &AgentPack,
    doctrines: &DoctrineManifest,
    output_path: &Path,
) -> Result<String, String> {
    let mut output = generated_document(&format!(
        "{} agent doctrine pack",
        title_case(pack.id.as_str())
    ));
    output.push('\n');
    output.push_str(&pack.purpose);
    output.push('\n');

    let mut included = BTreeSet::new();
    for path in &pack.canonical_sources {
        append_unique_source(root, path, output_path, &mut included, &mut output)?;
    }
    for doctrine_id in &pack.doctrine_selections {
        let doctrine = doctrines
            .doctrines
            .iter()
            .find(|entry| entry.id == *doctrine_id)
            .ok_or_else(|| format!("agent {} selects unknown doctrine {doctrine_id}", pack.id))?;
        append_unique_source(
            root,
            &doctrine.normative_path,
            output_path,
            &mut included,
            &mut output,
        )?;
    }
    for path in &pack.review_checklists {
        append_unique_source(root, path, output_path, &mut included, &mut output)?;
    }
    Ok(normalize_final_newline(output))
}

fn append_sources(
    root: &Path,
    paths: &[&str],
    output_path: &Path,
    output: &mut String,
) -> Result<(), String> {
    for path in paths {
        append_source(root, path, output_path, output)?;
    }
    Ok(())
}

fn append_unique_source(
    root: &Path,
    path: &str,
    output_path: &Path,
    included: &mut BTreeSet<String>,
    output: &mut String,
) -> Result<(), String> {
    if included.insert(path.to_owned()) {
        append_source(root, path, output_path, output)?;
    }
    Ok(())
}

fn append_source(
    root: &Path,
    relative: &str,
    output_path: &Path,
    output: &mut String,
) -> Result<(), String> {
    let relative_path = validate_relative_path(relative, "canonical source")?;
    let path = root.join(&relative_path);
    let content =
        fs::read_to_string(&path).map_err(|error| format!("cannot read {relative}: {error}"))?;
    let content = rewrite_relative_links(root, &relative_path, output_path, &content)?;
    output.push_str("\n---\n\n## Source: `");
    output.push_str(relative);
    output.push_str("`\n\n");
    output.push_str(content.trim_end());
    output.push('\n');
    Ok(())
}

fn validate_manifest_paths(
    doctrines: &DoctrineManifest,
    agents: &AgentManifest,
) -> Result<(), String> {
    for doctrine in &doctrines.doctrines {
        validate_relative_path(&doctrine.package_path, "doctrine package_path")?;
        validate_relative_path(&doctrine.normative_path, "doctrine normative_path")?;
    }

    for pack in &agents.packs {
        for source in pack.canonical_sources.iter().chain(&pack.review_checklists) {
            validate_relative_path(source, "agent canonical source")?;
        }

        let output = validate_relative_path(&pack.output_path, "agent output_path")?;
        if !output.starts_with("dist/agents")
            || output.extension().and_then(|extension| extension.to_str()) != Some("md")
        {
            return Err(format!(
                "agent output_path must name a Markdown file under dist/agents: {}",
                pack.output_path
            ));
        }
    }
    Ok(())
}

fn validate_relative_path(value: &str, field: &str) -> Result<PathBuf, String> {
    if value.is_empty()
        || value.starts_with('/')
        || value.ends_with('/')
        || value.contains('\\')
        || value
            .split('/')
            .any(|component| component.is_empty() || matches!(component, "." | ".."))
        || !value.bytes().all(|byte| {
            byte.is_ascii_alphabetic()
                || byte.is_ascii_digit()
                || matches!(byte, b'.' | b'_' | b'-' | b'/')
        })
    {
        return Err(format!(
            "{field} is not a normalized repository-relative path: {value:?}"
        ));
    }

    let path = PathBuf::from(value);
    if path
        .components()
        .any(|component| !matches!(component, Component::Normal(_)))
    {
        return Err(format!(
            "{field} contains a non-normal path component: {value:?}"
        ));
    }
    Ok(path)
}

fn validate_curated_inventory(root: &Path) -> Result<(), String> {
    for (directory, expected) in [
        ("foundations", FOUNDATION_FILES),
        ("patterns", PATTERN_FILES),
        ("boundaries", BOUNDARY_FILES),
        ("reviews", REVIEW_FILES),
    ] {
        let expected: BTreeSet<PathBuf> = expected.iter().map(PathBuf::from).collect();
        let actual: BTreeSet<PathBuf> = all_files(&root.join(directory))?
            .into_iter()
            .filter(|path| path.extension().and_then(|extension| extension.to_str()) == Some("md"))
            .map(|path| {
                path.strip_prefix(root)
                    .map(Path::to_path_buf)
                    .map_err(|error| {
                        format!(
                            "cannot relativize inventory path {}: {error}",
                            path.display()
                        )
                    })
            })
            .collect::<Result<_, _>>()?;

        if actual != expected {
            let missing = expected
                .difference(&actual)
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>();
            let unbundled = actual
                .difference(&expected)
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>();
            return Err(format!(
                "{directory} bundle inventory differs from disk; missing [{}], unbundled [{}]",
                missing.join(", "),
                unbundled.join(", ")
            ));
        }
    }
    Ok(())
}

fn rewrite_relative_links(
    root: &Path,
    source_path: &Path,
    output_path: &Path,
    content: &str,
) -> Result<String, String> {
    let mut rewritten = String::with_capacity(content.len());
    let mut in_fence = false;

    for line in content.split_inclusive('\n') {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") || trimmed.starts_with("~~~") {
            in_fence = !in_fence;
            rewritten.push_str(line);
        } else if in_fence {
            rewritten.push_str(line);
        } else {
            rewritten.push_str(&rewrite_inline_links(root, source_path, output_path, line)?);
        }
    }

    Ok(rewritten)
}

fn rewrite_inline_links(
    root: &Path,
    source_path: &Path,
    output_path: &Path,
    line: &str,
) -> Result<String, String> {
    let mut rewritten = String::with_capacity(line.len());
    let mut cursor = 0;

    while let Some(offset) = line[cursor..].find("](") {
        let destination_start = cursor + offset + 2;
        rewritten.push_str(&line[cursor..destination_start]);
        let Some(close_offset) = line[destination_start..].find(')') else {
            rewritten.push_str(&line[destination_start..]);
            return Ok(rewritten);
        };
        let destination_end = destination_start + close_offset;
        let destination = &line[destination_start..destination_end];
        rewritten.push_str(&rewrite_destination(
            root,
            source_path,
            output_path,
            destination,
        )?);
        rewritten.push(')');
        cursor = destination_end + 1;
    }

    rewritten.push_str(&line[cursor..]);
    Ok(rewritten)
}

fn rewrite_destination(
    root: &Path,
    source_path: &Path,
    output_path: &Path,
    destination: &str,
) -> Result<String, String> {
    let leading = destination.len() - destination.trim_start().len();
    let trimmed = destination.trim_start();
    let (bracketed, target_start, target_end) = if let Some(rest) = trimmed.strip_prefix('<') {
        let Some(end) = rest.find('>') else {
            return Ok(destination.to_owned());
        };
        (true, 1, end + 1)
    } else {
        let end = trimmed.find(char::is_whitespace).unwrap_or(trimmed.len());
        (false, 0, end)
    };
    let target = &trimmed[target_start..target_end];

    if !is_relative_link(target) {
        return Ok(destination.to_owned());
    }

    let suffix_index = target.find(['#', '?']).unwrap_or(target.len());
    let path_part = &target[..suffix_index];
    let suffix = &target[suffix_index..];
    if path_part.is_empty() {
        return Ok(destination.to_owned());
    }

    let resolved = resolve_link_target(source_path, path_part)?;
    let absolute_target = root.join(&resolved);
    if !absolute_target.exists() {
        return Err(format!(
            "{} links to missing repository path {path_part:?}",
            source_path.display()
        ));
    }
    let output_parent = output_path
        .parent()
        .ok_or_else(|| format!("generated output {} has no parent", output_path.display()))?;
    let relative = relative_path(output_parent, &resolved);
    let mut replacement = relative.to_string_lossy().replace('\\', "/");
    if path_part.ends_with('/') {
        replacement.push('/');
    }
    replacement.push_str(suffix);

    let mut result = String::with_capacity(destination.len() + replacement.len());
    result.push_str(&destination[..leading]);
    if bracketed {
        result.push('<');
    }
    result.push_str(&replacement);
    if bracketed {
        result.push('>');
    }
    result.push_str(&trimmed[target_end + usize::from(bracketed)..]);
    Ok(result)
}

fn is_relative_link(target: &str) -> bool {
    if target.is_empty() || target.starts_with(['#', '/', '?']) || target.starts_with("//") {
        return false;
    }
    let path_end = target.find(['/', '#', '?']).unwrap_or(target.len());
    !target[..path_end].contains(':')
}

fn resolve_link_target(source_path: &Path, target: &str) -> Result<PathBuf, String> {
    let mut components: Vec<PathBuf> = source_path
        .parent()
        .into_iter()
        .flat_map(Path::components)
        .filter_map(|component| match component {
            Component::Normal(value) => Some(PathBuf::from(value)),
            _ => None,
        })
        .collect();

    for component in Path::new(target).components() {
        match component {
            Component::Normal(value) => components.push(PathBuf::from(value)),
            Component::CurDir => {}
            Component::ParentDir => {
                if components.pop().is_none() {
                    return Err(format!(
                        "{} link {target:?} escapes the repository",
                        source_path.display()
                    ));
                }
            }
            Component::RootDir | Component::Prefix(_) => {
                return Err(format!(
                    "{} link {target:?} is not repository-relative",
                    source_path.display()
                ));
            }
        }
    }

    Ok(components.into_iter().collect())
}

fn relative_path(from_directory: &Path, to: &Path) -> PathBuf {
    let from = from_directory.components().collect::<Vec<_>>();
    let to = to.components().collect::<Vec<_>>();
    let shared = from
        .iter()
        .zip(&to)
        .take_while(|(left, right)| left == right)
        .count();

    let mut relative = PathBuf::new();
    for _ in shared..from.len() {
        relative.push("..");
    }
    for component in &to[shared..] {
        relative.push(component.as_os_str());
    }
    relative
}

fn generated_document(title: &str) -> String {
    let mut output = String::from(GENERATED_BANNER);
    output.push('\n');
    output.push_str("# ");
    output.push_str(title);
    output.push('\n');
    output
}

fn normalize_final_newline(mut text: String) -> String {
    let length = text.trim_end().len();
    text.truncate(length);
    text.push('\n');
    text
}

fn read_yaml<T: for<'de> Deserialize<'de>>(root: &Path, relative: &str) -> Result<T, String> {
    let text = fs::read_to_string(root.join(relative))
        .map_err(|error| format!("cannot read {relative}: {error}"))?;
    serde_yaml_ng::from_str(&text).map_err(|error| format!("cannot parse {relative}: {error}"))
}

fn title_case(value: &str) -> String {
    let mut characters = value.chars();
    let Some(first) = characters.next() else {
        return String::new();
    };
    first.to_uppercase().chain(characters).collect()
}

fn generate(root: &Path, outputs: &[GeneratedFile]) -> Result<(), String> {
    let mut updated = 0;
    for output in outputs {
        let path = root.join(&output.path);
        let parent = path
            .parent()
            .ok_or_else(|| format!("output {} has no parent", output.path.display()))?;
        fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
        let current = fs::read_to_string(&path).ok();
        if current.as_deref() != Some(output.content.as_str()) {
            fs::write(&path, &output.content)
                .map_err(|error| format!("cannot write {}: {error}", output.path.display()))?;
            updated += 1;
        }
    }
    println!(
        "bundle-agent-context: updated {updated} of {} generated file(s)",
        outputs.len()
    );
    Ok(())
}

fn check(root: &Path, outputs: &[GeneratedFile]) -> Result<(), String> {
    let mut drift = Vec::new();
    let expected: BTreeSet<PathBuf> = outputs.iter().map(|output| output.path.clone()).collect();

    for output in outputs {
        let path = root.join(&output.path);
        match fs::read_to_string(&path) {
            Ok(current) if current == output.content => {}
            Ok(_) => drift.push(format!("changed: {}", output.path.display())),
            Err(error) => drift.push(format!("missing: {} ({error})", output.path.display())),
        }
    }

    for path in all_files(&root.join("dist"))? {
        let relative = path
            .strip_prefix(root)
            .map_err(|error| format!("cannot relativize {}: {error}", path.display()))?
            .to_path_buf();
        if !expected.contains(&relative) {
            drift.push(format!("unexpected: {}", relative.display()));
        }
    }

    if drift.is_empty() {
        println!("bundle-agent-context: generated files are current");
        Ok(())
    } else {
        drift.sort();
        Err(format!("generated drift detected:\n{}", drift.join("\n")))
    }
}

/// Every file under `directory`, sorted.
///
/// Every directory this tool walks is one the repository requires, so any failure to
/// enumerate one aborts generation. Returning an empty list instead made a walk that
/// observed nothing indistinguishable from a directory that is genuinely empty: with
/// `rfcs/accepted` unlistable, generation rewrote the accepted-RFC index from its three
/// rows to "no accepted RFCs" and exited zero.
fn all_files(directory: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_files(directory, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_files(directory: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("cannot enumerate {}: {error}", directory.display()))?;
    // A per-entry failure is discarded by `filter_map(Result::ok)`, which drops a file
    // from the walk as quietly as an unreadable parent dropped all of them.
    for entry in entries {
        let entry = entry
            .map_err(|error| format!("cannot read an entry of {}: {error}", directory.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, files)?;
        } else if path.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        GENERATED_BANNER, GeneratedFile, all_files, append_source, check, generated_document,
        normalize_final_newline, rewrite_relative_links, title_case, validate_relative_path,
    };
    use std::fs;
    use std::path::Path;

    #[test]
    fn generated_document_starts_with_required_banner() {
        let document = generated_document("Example");
        assert!(document.starts_with(GENERATED_BANNER));
        assert!(document.contains("# Example\n"));
    }

    #[test]
    fn source_append_has_provenance_and_normalized_tail() {
        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-test-{}",
            std::process::id()
        ));
        fs::create_dir_all(&temporary).expect("create temporary test directory");
        fs::write(temporary.join("source.md"), "# Source\n\nBody\n\n").expect("write test source");

        let mut output = String::new();
        append_source(
            &temporary,
            "source.md",
            Path::new("dist/output.md"),
            &mut output,
        )
        .expect("append source");
        let output = normalize_final_newline(output);

        assert!(output.contains("## Source: `source.md`"));
        assert!(output.ends_with("Body\n"));
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }

    #[test]
    fn role_title_is_stable() {
        assert_eq!(title_case("planner"), "Planner");
        assert_eq!(title_case(""), "");
    }

    #[test]
    fn relocated_sources_link_back_to_canonical_files() {
        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-links-{}",
            std::process::id()
        ));
        fs::create_dir_all(temporary.join("foundations")).expect("create foundation directory");
        fs::create_dir_all(temporary.join("agents")).expect("create agent directory");
        fs::write(
            temporary.join("foundations/invariants.md"),
            "# Invariants\n",
        )
        .expect("write target");
        let source = "Read [invariants](../foundations/invariants.md#inventory).\n";

        let rewritten = rewrite_relative_links(
            &temporary,
            Path::new("agents/shared.md"),
            Path::new("dist/agents/shared.md"),
            source,
        )
        .expect("rewrite relative link");

        assert_eq!(
            rewritten,
            "Read [invariants](../../foundations/invariants.md#inventory).\n"
        );
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }

    #[test]
    fn manifest_paths_cannot_escape_repository() {
        assert!(validate_relative_path("agents/shared.md", "test").is_ok());
        assert!(validate_relative_path("../outside.md", "test").is_err());
        assert!(validate_relative_path("agents/../outside.md", "test").is_err());
        assert!(validate_relative_path("/outside.md", "test").is_err());
    }

    /// A directory the bundler cannot enumerate must abort the walk. Returning an empty
    /// list made an unlistable `rfcs/accepted` indistinguishable from an empty one, so
    /// generation rewrote the accepted-RFC index to "no accepted RFCs" and exited zero.
    #[cfg(unix)]
    #[test]
    fn an_unlistable_directory_aborts_the_walk() {
        use std::os::unix::fs::PermissionsExt;

        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-unlistable-{}",
            std::process::id()
        ));
        let locked = temporary.join("locked");
        fs::create_dir_all(&locked).expect("create directory");
        fs::write(locked.join("entry.md"), "body\n").expect("write test entry");
        fs::set_permissions(&locked, fs::Permissions::from_mode(0o111))
            .expect("remove read permission");

        // A process that overrides permission bits cannot construct the condition.
        let enforced = fs::read_dir(&locked).is_err();
        let walked = all_files(&locked);

        fs::set_permissions(&locked, fs::Permissions::from_mode(0o755))
            .expect("restore directory permissions");
        fs::remove_dir_all(&temporary).expect("remove temporary test directory");

        if enforced {
            let error = walked.expect_err("an unlistable directory must abort the walk");
            assert!(error.contains("cannot enumerate"), "{error}");
        }
    }

    #[test]
    fn check_rejects_non_markdown_orphans_in_dist() {
        let temporary = std::env::temp_dir().join(format!(
            "doctrines-rust-bundler-orphans-{}",
            std::process::id()
        ));
        fs::create_dir_all(temporary.join("dist")).expect("create dist directory");
        fs::write(temporary.join("dist/expected.md"), "expected\n").expect("write expected file");
        fs::write(temporary.join("dist/orphan.bin"), [0_u8, 1, 2]).expect("write orphan file");
        let outputs = [GeneratedFile {
            path: Path::new("dist/expected.md").to_path_buf(),
            content: "expected\n".to_owned(),
        }];

        let error = check(&temporary, &outputs).expect_err("orphan must fail check mode");
        assert!(error.contains("unexpected: dist/orphan.bin"));
        fs::remove_dir_all(temporary).expect("remove temporary test directory");
    }
}
