[package]
name = "doctrine-compile-fail"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
staged-protocol = { version = "0.6.0", path = "../staged-protocol" }
trybuild.workspace = true

[lints]
workspace = true
